// Generated by scripts/build-photos.mjs. Edit scripts/photos.json and re-run it.

export type Photo = {
  id: string;
  full: string;
  thumb: string;
  width: number;
  height: number;
  alt: string;
  settings: string;
};

export type Album = {
  slug: string;
  title: string;
  place: string;
  date: string;
  photos: Photo[];
};

export const CAMERA = "Sony a6300";

export const ALBUMS: Album[] = [
  {
    "slug": "toronto-islands",
    "title": "Toronto Islands",
    "place": "Toronto",
    "date": "Jul 2026",
    "photos": [
      {
        "id": "toronto-islands/DSC00099",
        "full": "/photos/toronto-islands/DSC00099.webp",
        "thumb": "/photos/toronto-islands/DSC00099-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Toronto Islands, frame 1",
        "settings": "50mm · ƒ/5.6 · 1/400s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00098",
        "full": "/photos/toronto-islands/DSC00098.webp",
        "thumb": "/photos/toronto-islands/DSC00098-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 2",
        "settings": "50mm · ƒ/6.3 · 1/320s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00001",
        "full": "/photos/toronto-islands/DSC00001.webp",
        "thumb": "/photos/toronto-islands/DSC00001-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Toronto Islands, frame 3",
        "settings": "50mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00008",
        "full": "/photos/toronto-islands/DSC00008.webp",
        "thumb": "/photos/toronto-islands/DSC00008-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 4",
        "settings": "42mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00011",
        "full": "/photos/toronto-islands/DSC00011.webp",
        "thumb": "/photos/toronto-islands/DSC00011-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 5",
        "settings": "41mm · ƒ/5.6 · 1/1600s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00012",
        "full": "/photos/toronto-islands/DSC00012.webp",
        "thumb": "/photos/toronto-islands/DSC00012-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 6",
        "settings": "16mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00013",
        "full": "/photos/toronto-islands/DSC00013.webp",
        "thumb": "/photos/toronto-islands/DSC00013-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 7",
        "settings": "50mm · ƒ/5.6 · 1/1600s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00019",
        "full": "/photos/toronto-islands/DSC00019.webp",
        "thumb": "/photos/toronto-islands/DSC00019-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 8",
        "settings": "50mm · ƒ/6.3 · 1/320s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00024",
        "full": "/photos/toronto-islands/DSC00024.webp",
        "thumb": "/photos/toronto-islands/DSC00024-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 9",
        "settings": "16mm · ƒ/5.6 · 1/2500s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00058",
        "full": "/photos/toronto-islands/DSC00058.webp",
        "thumb": "/photos/toronto-islands/DSC00058-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 10",
        "settings": "50mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00059",
        "full": "/photos/toronto-islands/DSC00059.webp",
        "thumb": "/photos/toronto-islands/DSC00059-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 11",
        "settings": "50mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00062",
        "full": "/photos/toronto-islands/DSC00062.webp",
        "thumb": "/photos/toronto-islands/DSC00062-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Toronto Islands, frame 12",
        "settings": "50mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00063",
        "full": "/photos/toronto-islands/DSC00063.webp",
        "thumb": "/photos/toronto-islands/DSC00063-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Toronto Islands, frame 13",
        "settings": "50mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00067",
        "full": "/photos/toronto-islands/DSC00067.webp",
        "thumb": "/photos/toronto-islands/DSC00067-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 14",
        "settings": "50mm · ƒ/6.3 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00070",
        "full": "/photos/toronto-islands/DSC00070.webp",
        "thumb": "/photos/toronto-islands/DSC00070-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 15",
        "settings": "47mm · ƒ/6.3 · 1/1000s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00071",
        "full": "/photos/toronto-islands/DSC00071.webp",
        "thumb": "/photos/toronto-islands/DSC00071-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 16",
        "settings": "47mm · ƒ/6.3 · 1/1000s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00073",
        "full": "/photos/toronto-islands/DSC00073.webp",
        "thumb": "/photos/toronto-islands/DSC00073-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 17",
        "settings": "46mm · ƒ/6.3 · 1/1000s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00075",
        "full": "/photos/toronto-islands/DSC00075.webp",
        "thumb": "/photos/toronto-islands/DSC00075-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 18",
        "settings": "50mm · ƒ/6.3 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00076",
        "full": "/photos/toronto-islands/DSC00076.webp",
        "thumb": "/photos/toronto-islands/DSC00076-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 19",
        "settings": "50mm · ƒ/6.3 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00077",
        "full": "/photos/toronto-islands/DSC00077.webp",
        "thumb": "/photos/toronto-islands/DSC00077-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 20",
        "settings": "50mm · ƒ/6.3 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00078",
        "full": "/photos/toronto-islands/DSC00078.webp",
        "thumb": "/photos/toronto-islands/DSC00078-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 21",
        "settings": "50mm · ƒ/6.3 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00081",
        "full": "/photos/toronto-islands/DSC00081.webp",
        "thumb": "/photos/toronto-islands/DSC00081-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 22",
        "settings": "21mm · ƒ/6.3 · 1/2500s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00087",
        "full": "/photos/toronto-islands/DSC00087.webp",
        "thumb": "/photos/toronto-islands/DSC00087-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 23",
        "settings": "16mm · ƒ/6.3 · 1/250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00088",
        "full": "/photos/toronto-islands/DSC00088.webp",
        "thumb": "/photos/toronto-islands/DSC00088-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 24",
        "settings": "34mm · ƒ/6.3 · 1/250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00089",
        "full": "/photos/toronto-islands/DSC00089.webp",
        "thumb": "/photos/toronto-islands/DSC00089-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 25",
        "settings": "50mm · ƒ/6.3 · 1/250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00090",
        "full": "/photos/toronto-islands/DSC00090.webp",
        "thumb": "/photos/toronto-islands/DSC00090-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Toronto Islands, frame 26",
        "settings": "23mm · ƒ/6.3 · 1/160s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00096",
        "full": "/photos/toronto-islands/DSC00096.webp",
        "thumb": "/photos/toronto-islands/DSC00096-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 27",
        "settings": "45mm · ƒ/6.3 · 1/1600s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00097",
        "full": "/photos/toronto-islands/DSC00097.webp",
        "thumb": "/photos/toronto-islands/DSC00097-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 28",
        "settings": "41mm · ƒ/6.3 · 1/250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00103",
        "full": "/photos/toronto-islands/DSC00103.webp",
        "thumb": "/photos/toronto-islands/DSC00103-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 29",
        "settings": "50mm · ƒ/5.6 · 1/320s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00104",
        "full": "/photos/toronto-islands/DSC00104.webp",
        "thumb": "/photos/toronto-islands/DSC00104-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 30",
        "settings": "24mm · ƒ/5.6 · 1/160s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC00105",
        "full": "/photos/toronto-islands/DSC00105.webp",
        "thumb": "/photos/toronto-islands/DSC00105-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 31",
        "settings": "45mm · ƒ/5.6 · 1/100s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC09979",
        "full": "/photos/toronto-islands/DSC09979.webp",
        "thumb": "/photos/toronto-islands/DSC09979-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 32",
        "settings": "16mm · ƒ/5.6 · 1/800s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC09981",
        "full": "/photos/toronto-islands/DSC09981.webp",
        "thumb": "/photos/toronto-islands/DSC09981-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 33",
        "settings": "16mm · ƒ/5.6 · 1/1600s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC09982",
        "full": "/photos/toronto-islands/DSC09982.webp",
        "thumb": "/photos/toronto-islands/DSC09982-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 34",
        "settings": "41mm · ƒ/5.6 · 1/1000s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC09984",
        "full": "/photos/toronto-islands/DSC09984.webp",
        "thumb": "/photos/toronto-islands/DSC09984-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Toronto Islands, frame 35",
        "settings": "35mm · ƒ/5.6 · 1/640s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC09986",
        "full": "/photos/toronto-islands/DSC09986.webp",
        "thumb": "/photos/toronto-islands/DSC09986-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Toronto Islands, frame 36",
        "settings": "50mm · ƒ/5.6 · 1/640s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC09987",
        "full": "/photos/toronto-islands/DSC09987.webp",
        "thumb": "/photos/toronto-islands/DSC09987-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 37",
        "settings": "16mm · ƒ/5.6 · 1/1250s · ISO 100"
      },
      {
        "id": "toronto-islands/DSC09997",
        "full": "/photos/toronto-islands/DSC09997.webp",
        "thumb": "/photos/toronto-islands/DSC09997-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Toronto Islands, frame 38",
        "settings": "50mm · ƒ/5.6 · 1/1000s · ISO 100"
      }
    ]
  },
  {
    "slug": "lions-head",
    "title": "Lion's Head",
    "place": "",
    "date": "Jun 2026",
    "photos": [
      {
        "id": "lions-head/DSC09971",
        "full": "/photos/lions-head/DSC09971.webp",
        "thumb": "/photos/lions-head/DSC09971-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Lion's Head, frame 1",
        "settings": "30mm · ƒ/5.6 · 1/60s · ISO 125"
      },
      {
        "id": "lions-head/DSC09804",
        "full": "/photos/lions-head/DSC09804.webp",
        "thumb": "/photos/lions-head/DSC09804-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Lion's Head, frame 2",
        "settings": "25mm · ƒ/5.6 · 1/60s · ISO 125"
      },
      {
        "id": "lions-head/DSC09829",
        "full": "/photos/lions-head/DSC09829.webp",
        "thumb": "/photos/lions-head/DSC09829-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Lion's Head, frame 3",
        "settings": "34mm · ƒ/5.6 · 1/60s · ISO 125"
      },
      {
        "id": "lions-head/DSC09838",
        "full": "/photos/lions-head/DSC09838.webp",
        "thumb": "/photos/lions-head/DSC09838-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Lion's Head, frame 4",
        "settings": "30mm · ƒ/5.6 · 1/60s · ISO 160"
      },
      {
        "id": "lions-head/DSC09907",
        "full": "/photos/lions-head/DSC09907.webp",
        "thumb": "/photos/lions-head/DSC09907-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Lion's Head, frame 5",
        "settings": "16mm · ƒ/5 · 1/8s · ISO 1600"
      },
      {
        "id": "lions-head/DSC09915",
        "full": "/photos/lions-head/DSC09915.webp",
        "thumb": "/photos/lions-head/DSC09915-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Lion's Head, frame 6",
        "settings": "16mm · ƒ/5 · 1/60s · ISO 500"
      },
      {
        "id": "lions-head/DSC09968",
        "full": "/photos/lions-head/DSC09968.webp",
        "thumb": "/photos/lions-head/DSC09968-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Lion's Head, frame 7",
        "settings": "16mm · ƒ/5.6 · 1/60s · ISO 1250"
      },
      {
        "id": "lions-head/DSC09970",
        "full": "/photos/lions-head/DSC09970.webp",
        "thumb": "/photos/lions-head/DSC09970-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Lion's Head, frame 8",
        "settings": "16mm · ƒ/5.6 · 1/80s · ISO 100"
      }
    ]
  },
  {
    "slug": "streetsville",
    "title": "Streetsville",
    "place": "Mississauga",
    "date": "May 2026",
    "photos": [
      {
        "id": "streetsville/DSC09649",
        "full": "/photos/streetsville/DSC09649.webp",
        "thumb": "/photos/streetsville/DSC09649-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Streetsville, frame 1",
        "settings": "18mm · ƒ/4.5 · 1/1000s · ISO 100"
      },
      {
        "id": "streetsville/DSC09652",
        "full": "/photos/streetsville/DSC09652.webp",
        "thumb": "/photos/streetsville/DSC09652-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Streetsville, frame 2",
        "settings": "32mm · ƒ/5 · 1/800s · ISO 100"
      },
      {
        "id": "streetsville/DSC09674",
        "full": "/photos/streetsville/DSC09674.webp",
        "thumb": "/photos/streetsville/DSC09674-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Streetsville, frame 3",
        "settings": "50mm · ƒ/5.6 · 1/400s · ISO 100"
      },
      {
        "id": "streetsville/DSC09680",
        "full": "/photos/streetsville/DSC09680.webp",
        "thumb": "/photos/streetsville/DSC09680-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Streetsville, frame 4",
        "settings": "28mm · ƒ/4.5 · 1/640s · ISO 100"
      }
    ]
  },
  {
    "slug": "home",
    "title": "Home",
    "place": "",
    "date": "Apr 2026",
    "photos": [
      {
        "id": "home/DSC08963",
        "full": "/photos/home/DSC08963.webp",
        "thumb": "/photos/home/DSC08963-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Home, frame 1",
        "settings": "50mm · ƒ/16 · 1/4s · ISO 1600"
      },
      {
        "id": "home/DSC08964",
        "full": "/photos/home/DSC08964.webp",
        "thumb": "/photos/home/DSC08964-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Home, frame 2",
        "settings": "36mm · ƒ/16 · 0.5s · ISO 1600"
      },
      {
        "id": "home/DSC08967",
        "full": "/photos/home/DSC08967.webp",
        "thumb": "/photos/home/DSC08967-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Home, frame 3",
        "settings": "50mm · ƒ/16 · 1/4s · ISO 1600"
      },
      {
        "id": "home/DSC08968",
        "full": "/photos/home/DSC08968.webp",
        "thumb": "/photos/home/DSC08968-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Home, frame 4",
        "settings": "50mm · ƒ/16 · 1/4s · ISO 1600"
      },
      {
        "id": "home/DSC08969",
        "full": "/photos/home/DSC08969.webp",
        "thumb": "/photos/home/DSC08969-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Home, frame 5",
        "settings": "50mm · ƒ/16 · 0.3s · ISO 1600"
      }
    ]
  },
  {
    "slug": "san-diego",
    "title": "San Diego",
    "place": "California",
    "date": "Apr 2026",
    "photos": [
      {
        "id": "san-diego/DSC08556",
        "full": "/photos/san-diego/DSC08556.webp",
        "thumb": "/photos/san-diego/DSC08556-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 1",
        "settings": "16mm · ƒ/3.5 · 1/5s · ISO 6400"
      },
      {
        "id": "san-diego/DSC08565",
        "full": "/photos/san-diego/DSC08565.webp",
        "thumb": "/photos/san-diego/DSC08565-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 2",
        "settings": "16mm · ƒ/8 · 1/100s · ISO 100"
      },
      {
        "id": "san-diego/DSC08570",
        "full": "/photos/san-diego/DSC08570.webp",
        "thumb": "/photos/san-diego/DSC08570-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 3",
        "settings": "25mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "san-diego/DSC08632",
        "full": "/photos/san-diego/DSC08632.webp",
        "thumb": "/photos/san-diego/DSC08632-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 4",
        "settings": "50mm · ƒ/10 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08655",
        "full": "/photos/san-diego/DSC08655.webp",
        "thumb": "/photos/san-diego/DSC08655-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 5",
        "settings": "16mm · ƒ/11 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08656",
        "full": "/photos/san-diego/DSC08656.webp",
        "thumb": "/photos/san-diego/DSC08656-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 6",
        "settings": "16mm · ƒ/11 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08657",
        "full": "/photos/san-diego/DSC08657.webp",
        "thumb": "/photos/san-diego/DSC08657-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 7",
        "settings": "26mm · ƒ/11 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08658",
        "full": "/photos/san-diego/DSC08658.webp",
        "thumb": "/photos/san-diego/DSC08658-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 8",
        "settings": "40mm · ƒ/8 · 1/320s · ISO 100"
      },
      {
        "id": "san-diego/DSC08659",
        "full": "/photos/san-diego/DSC08659.webp",
        "thumb": "/photos/san-diego/DSC08659-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 9",
        "settings": "27mm · ƒ/11 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08661",
        "full": "/photos/san-diego/DSC08661.webp",
        "thumb": "/photos/san-diego/DSC08661-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 10",
        "settings": "16mm · ƒ/8 · 1/100s · ISO 100"
      },
      {
        "id": "san-diego/DSC08693",
        "full": "/photos/san-diego/DSC08693.webp",
        "thumb": "/photos/san-diego/DSC08693-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 11",
        "settings": "16mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08695",
        "full": "/photos/san-diego/DSC08695.webp",
        "thumb": "/photos/san-diego/DSC08695-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 12",
        "settings": "43mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08696",
        "full": "/photos/san-diego/DSC08696.webp",
        "thumb": "/photos/san-diego/DSC08696-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 13",
        "settings": "41mm · ƒ/11 · 1/250s · ISO 100"
      },
      {
        "id": "san-diego/DSC08697",
        "full": "/photos/san-diego/DSC08697.webp",
        "thumb": "/photos/san-diego/DSC08697-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 14",
        "settings": "36mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08699",
        "full": "/photos/san-diego/DSC08699.webp",
        "thumb": "/photos/san-diego/DSC08699-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 15",
        "settings": "16mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08703",
        "full": "/photos/san-diego/DSC08703.webp",
        "thumb": "/photos/san-diego/DSC08703-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 16",
        "settings": "18mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08713",
        "full": "/photos/san-diego/DSC08713.webp",
        "thumb": "/photos/san-diego/DSC08713-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 17",
        "settings": "23mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08714",
        "full": "/photos/san-diego/DSC08714.webp",
        "thumb": "/photos/san-diego/DSC08714-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 18",
        "settings": "50mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08724",
        "full": "/photos/san-diego/DSC08724.webp",
        "thumb": "/photos/san-diego/DSC08724-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 19",
        "settings": "16mm · ƒ/7.1 · 1/250s · ISO 100"
      },
      {
        "id": "san-diego/DSC08741",
        "full": "/photos/san-diego/DSC08741.webp",
        "thumb": "/photos/san-diego/DSC08741-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 20",
        "settings": "50mm · ƒ/9 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08768",
        "full": "/photos/san-diego/DSC08768.webp",
        "thumb": "/photos/san-diego/DSC08768-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 21",
        "settings": "16mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08769",
        "full": "/photos/san-diego/DSC08769.webp",
        "thumb": "/photos/san-diego/DSC08769-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 22",
        "settings": "23mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08774",
        "full": "/photos/san-diego/DSC08774.webp",
        "thumb": "/photos/san-diego/DSC08774-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 23",
        "settings": "46mm · ƒ/11 · 1/400s · ISO 100"
      },
      {
        "id": "san-diego/DSC08775",
        "full": "/photos/san-diego/DSC08775.webp",
        "thumb": "/photos/san-diego/DSC08775-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 24",
        "settings": "17mm · ƒ/11 · 1/400s · ISO 100"
      },
      {
        "id": "san-diego/DSC08777",
        "full": "/photos/san-diego/DSC08777.webp",
        "thumb": "/photos/san-diego/DSC08777-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 25",
        "settings": "24mm · ƒ/11 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08778",
        "full": "/photos/san-diego/DSC08778.webp",
        "thumb": "/photos/san-diego/DSC08778-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 26",
        "settings": "31mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "san-diego/DSC08779",
        "full": "/photos/san-diego/DSC08779.webp",
        "thumb": "/photos/san-diego/DSC08779-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 27",
        "settings": "16mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08807",
        "full": "/photos/san-diego/DSC08807.webp",
        "thumb": "/photos/san-diego/DSC08807-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 28",
        "settings": "35mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08812",
        "full": "/photos/san-diego/DSC08812.webp",
        "thumb": "/photos/san-diego/DSC08812-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 29",
        "settings": "41mm · ƒ/9 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08815",
        "full": "/photos/san-diego/DSC08815.webp",
        "thumb": "/photos/san-diego/DSC08815-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 30",
        "settings": "29mm · ƒ/11 · 1/250s · ISO 100"
      },
      {
        "id": "san-diego/DSC08816",
        "full": "/photos/san-diego/DSC08816.webp",
        "thumb": "/photos/san-diego/DSC08816-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 31",
        "settings": "29mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08818",
        "full": "/photos/san-diego/DSC08818.webp",
        "thumb": "/photos/san-diego/DSC08818-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 32",
        "settings": "50mm · ƒ/10 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08822",
        "full": "/photos/san-diego/DSC08822.webp",
        "thumb": "/photos/san-diego/DSC08822-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 33",
        "settings": "28mm · ƒ/11 · 1/200s · ISO 100"
      },
      {
        "id": "san-diego/DSC08826",
        "full": "/photos/san-diego/DSC08826.webp",
        "thumb": "/photos/san-diego/DSC08826-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 34",
        "settings": "16mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08827",
        "full": "/photos/san-diego/DSC08827.webp",
        "thumb": "/photos/san-diego/DSC08827-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 35",
        "settings": "16mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08828",
        "full": "/photos/san-diego/DSC08828.webp",
        "thumb": "/photos/san-diego/DSC08828-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 36",
        "settings": "50mm · ƒ/9 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08830",
        "full": "/photos/san-diego/DSC08830.webp",
        "thumb": "/photos/san-diego/DSC08830-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 37",
        "settings": "39mm · ƒ/11 · 1/160s · ISO 100"
      },
      {
        "id": "san-diego/DSC08838",
        "full": "/photos/san-diego/DSC08838.webp",
        "thumb": "/photos/san-diego/DSC08838-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 38",
        "settings": "39mm · ƒ/11 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08864",
        "full": "/photos/san-diego/DSC08864.webp",
        "thumb": "/photos/san-diego/DSC08864-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 39",
        "settings": "16mm · ƒ/9 · 1/100s · ISO 100"
      },
      {
        "id": "san-diego/DSC08865",
        "full": "/photos/san-diego/DSC08865.webp",
        "thumb": "/photos/san-diego/DSC08865-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 40",
        "settings": "16mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "san-diego/DSC08866",
        "full": "/photos/san-diego/DSC08866.webp",
        "thumb": "/photos/san-diego/DSC08866-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 41",
        "settings": "50mm · ƒ/10 · 1/125s · ISO 100"
      },
      {
        "id": "san-diego/DSC08881",
        "full": "/photos/san-diego/DSC08881.webp",
        "thumb": "/photos/san-diego/DSC08881-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 42",
        "settings": "16mm · ƒ/7.1 · 1/100s · ISO 100"
      },
      {
        "id": "san-diego/DSC08932",
        "full": "/photos/san-diego/DSC08932.webp",
        "thumb": "/photos/san-diego/DSC08932-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 43",
        "settings": "16mm · ƒ/16 · 1/60s · ISO 100"
      },
      {
        "id": "san-diego/DSC08933",
        "full": "/photos/san-diego/DSC08933.webp",
        "thumb": "/photos/san-diego/DSC08933-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 44",
        "settings": "50mm · ƒ/16 · 1/60s · ISO 200"
      },
      {
        "id": "san-diego/DSC08945",
        "full": "/photos/san-diego/DSC08945.webp",
        "thumb": "/photos/san-diego/DSC08945-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 45",
        "settings": "31mm · ƒ/16 · 1/60s · ISO 1000"
      },
      {
        "id": "san-diego/DSC08946",
        "full": "/photos/san-diego/DSC08946.webp",
        "thumb": "/photos/san-diego/DSC08946-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 46",
        "settings": "31mm · ƒ/16 · 1/60s · ISO 800"
      },
      {
        "id": "san-diego/DSC08948",
        "full": "/photos/san-diego/DSC08948.webp",
        "thumb": "/photos/san-diego/DSC08948-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "San Diego, frame 47",
        "settings": "16mm · ƒ/16 · 1/60s · ISO 1600"
      },
      {
        "id": "san-diego/DSC08949",
        "full": "/photos/san-diego/DSC08949.webp",
        "thumb": "/photos/san-diego/DSC08949-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "San Diego, frame 48",
        "settings": "16mm · ƒ/16 · 1/50s · ISO 1600"
      }
    ]
  },
  {
    "slug": "hollywood",
    "title": "Hollywood",
    "place": "Los Angeles",
    "date": "Apr 2026",
    "photos": [
      {
        "id": "hollywood/DSC08305",
        "full": "/photos/hollywood/DSC08305.webp",
        "thumb": "/photos/hollywood/DSC08305-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 1",
        "settings": "23mm · ƒ/20 · 1/60s · ISO 160"
      },
      {
        "id": "hollywood/DSC08353",
        "full": "/photos/hollywood/DSC08353.webp",
        "thumb": "/photos/hollywood/DSC08353-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 2",
        "settings": "50mm · ƒ/20 · 1/60s · ISO 125"
      },
      {
        "id": "hollywood/DSC08420",
        "full": "/photos/hollywood/DSC08420.webp",
        "thumb": "/photos/hollywood/DSC08420-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 3",
        "settings": "49mm · ƒ/22 · 1/60s · ISO 125"
      },
      {
        "id": "hollywood/DSC08465",
        "full": "/photos/hollywood/DSC08465.webp",
        "thumb": "/photos/hollywood/DSC08465-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 4",
        "settings": "28mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08471",
        "full": "/photos/hollywood/DSC08471.webp",
        "thumb": "/photos/hollywood/DSC08471-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 5",
        "settings": "50mm · ƒ/8 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08475",
        "full": "/photos/hollywood/DSC08475.webp",
        "thumb": "/photos/hollywood/DSC08475-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 6",
        "settings": "43mm · ƒ/8 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08476",
        "full": "/photos/hollywood/DSC08476.webp",
        "thumb": "/photos/hollywood/DSC08476-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 7",
        "settings": "27mm · ƒ/8 · 1/80s · ISO 100"
      },
      {
        "id": "hollywood/DSC08477",
        "full": "/photos/hollywood/DSC08477.webp",
        "thumb": "/photos/hollywood/DSC08477-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 8",
        "settings": "27mm · ƒ/8 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08479",
        "full": "/photos/hollywood/DSC08479.webp",
        "thumb": "/photos/hollywood/DSC08479-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 9",
        "settings": "16mm · ƒ/9 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08480",
        "full": "/photos/hollywood/DSC08480.webp",
        "thumb": "/photos/hollywood/DSC08480-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 10",
        "settings": "16mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08481",
        "full": "/photos/hollywood/DSC08481.webp",
        "thumb": "/photos/hollywood/DSC08481-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 11",
        "settings": "16mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08482",
        "full": "/photos/hollywood/DSC08482.webp",
        "thumb": "/photos/hollywood/DSC08482-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 12",
        "settings": "16mm · ƒ/9 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08510",
        "full": "/photos/hollywood/DSC08510.webp",
        "thumb": "/photos/hollywood/DSC08510-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Hollywood, frame 13",
        "settings": "18mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08515",
        "full": "/photos/hollywood/DSC08515.webp",
        "thumb": "/photos/hollywood/DSC08515-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Hollywood, frame 14",
        "settings": "34mm · ƒ/9 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08516",
        "full": "/photos/hollywood/DSC08516.webp",
        "thumb": "/photos/hollywood/DSC08516-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Hollywood, frame 15",
        "settings": "38mm · ƒ/9 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08517",
        "full": "/photos/hollywood/DSC08517.webp",
        "thumb": "/photos/hollywood/DSC08517-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Hollywood, frame 16",
        "settings": "38mm · ƒ/8 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08519",
        "full": "/photos/hollywood/DSC08519.webp",
        "thumb": "/photos/hollywood/DSC08519-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 17",
        "settings": "32mm · ƒ/8 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08521",
        "full": "/photos/hollywood/DSC08521.webp",
        "thumb": "/photos/hollywood/DSC08521-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 18",
        "settings": "19mm · ƒ/9 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08526",
        "full": "/photos/hollywood/DSC08526.webp",
        "thumb": "/photos/hollywood/DSC08526-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 19",
        "settings": "23mm · ƒ/10 · 1/100s · ISO 100"
      },
      {
        "id": "hollywood/DSC08528",
        "full": "/photos/hollywood/DSC08528.webp",
        "thumb": "/photos/hollywood/DSC08528-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Hollywood, frame 20",
        "settings": "27mm · ƒ/9 · 1/100s · ISO 100"
      }
    ]
  },
  {
    "slug": "grand-canyon",
    "title": "Grand Canyon",
    "place": "Arizona",
    "date": "Apr 2026",
    "photos": [
      {
        "id": "grand-canyon/DSC08025",
        "full": "/photos/grand-canyon/DSC08025.webp",
        "thumb": "/photos/grand-canyon/DSC08025-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 1",
        "settings": "38mm · ƒ/14 · 1/125s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08026",
        "full": "/photos/grand-canyon/DSC08026.webp",
        "thumb": "/photos/grand-canyon/DSC08026-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 2",
        "settings": "29mm · ƒ/14 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08030",
        "full": "/photos/grand-canyon/DSC08030.webp",
        "thumb": "/photos/grand-canyon/DSC08030-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 3",
        "settings": "17mm · ƒ/14 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08031",
        "full": "/photos/grand-canyon/DSC08031.webp",
        "thumb": "/photos/grand-canyon/DSC08031-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 4",
        "settings": "17mm · ƒ/14 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08032",
        "full": "/photos/grand-canyon/DSC08032.webp",
        "thumb": "/photos/grand-canyon/DSC08032-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 5",
        "settings": "17mm · ƒ/14 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08088",
        "full": "/photos/grand-canyon/DSC08088.webp",
        "thumb": "/photos/grand-canyon/DSC08088-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 6",
        "settings": "22mm · ƒ/14 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08092",
        "full": "/photos/grand-canyon/DSC08092.webp",
        "thumb": "/photos/grand-canyon/DSC08092-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 7",
        "settings": "16mm · ƒ/14 · 1/250s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08093",
        "full": "/photos/grand-canyon/DSC08093.webp",
        "thumb": "/photos/grand-canyon/DSC08093-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 8",
        "settings": "27mm · ƒ/14 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08094",
        "full": "/photos/grand-canyon/DSC08094.webp",
        "thumb": "/photos/grand-canyon/DSC08094-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 9",
        "settings": "16mm · ƒ/14 · 1/125s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08104",
        "full": "/photos/grand-canyon/DSC08104.webp",
        "thumb": "/photos/grand-canyon/DSC08104-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 10",
        "settings": "34mm · ƒ/14 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08110",
        "full": "/photos/grand-canyon/DSC08110.webp",
        "thumb": "/photos/grand-canyon/DSC08110-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 11",
        "settings": "23mm · ƒ/13 · 1/320s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08111",
        "full": "/photos/grand-canyon/DSC08111.webp",
        "thumb": "/photos/grand-canyon/DSC08111-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 12",
        "settings": "23mm · ƒ/13 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08112",
        "full": "/photos/grand-canyon/DSC08112.webp",
        "thumb": "/photos/grand-canyon/DSC08112-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 13",
        "settings": "16mm · ƒ/13 · 1/250s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08118",
        "full": "/photos/grand-canyon/DSC08118.webp",
        "thumb": "/photos/grand-canyon/DSC08118-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 14",
        "settings": "23mm · ƒ/13 · 1/250s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08119",
        "full": "/photos/grand-canyon/DSC08119.webp",
        "thumb": "/photos/grand-canyon/DSC08119-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 15",
        "settings": "16mm · ƒ/13 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08122",
        "full": "/photos/grand-canyon/DSC08122.webp",
        "thumb": "/photos/grand-canyon/DSC08122-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 16",
        "settings": "16mm · ƒ/13 · 1/250s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08123",
        "full": "/photos/grand-canyon/DSC08123.webp",
        "thumb": "/photos/grand-canyon/DSC08123-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 17",
        "settings": "16mm · ƒ/13 · 1/250s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08130",
        "full": "/photos/grand-canyon/DSC08130.webp",
        "thumb": "/photos/grand-canyon/DSC08130-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 18",
        "settings": "16mm · ƒ/13 · 1/250s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08142",
        "full": "/photos/grand-canyon/DSC08142.webp",
        "thumb": "/photos/grand-canyon/DSC08142-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 19",
        "settings": "23mm · ƒ/13 · 1/200s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08147",
        "full": "/photos/grand-canyon/DSC08147.webp",
        "thumb": "/photos/grand-canyon/DSC08147-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 20",
        "settings": "18mm · ƒ/14 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08152",
        "full": "/photos/grand-canyon/DSC08152.webp",
        "thumb": "/photos/grand-canyon/DSC08152-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 21",
        "settings": "24mm · ƒ/14 · 1/250s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08158",
        "full": "/photos/grand-canyon/DSC08158.webp",
        "thumb": "/photos/grand-canyon/DSC08158-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 22",
        "settings": "20mm · ƒ/18 · 1/125s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08159",
        "full": "/photos/grand-canyon/DSC08159.webp",
        "thumb": "/photos/grand-canyon/DSC08159-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 23",
        "settings": "16mm · ƒ/18 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08160",
        "full": "/photos/grand-canyon/DSC08160.webp",
        "thumb": "/photos/grand-canyon/DSC08160-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 24",
        "settings": "16mm · ƒ/18 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08167",
        "full": "/photos/grand-canyon/DSC08167.webp",
        "thumb": "/photos/grand-canyon/DSC08167-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 25",
        "settings": "16mm · ƒ/22 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08180",
        "full": "/photos/grand-canyon/DSC08180.webp",
        "thumb": "/photos/grand-canyon/DSC08180-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 26",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08181",
        "full": "/photos/grand-canyon/DSC08181.webp",
        "thumb": "/photos/grand-canyon/DSC08181-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 27",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08188",
        "full": "/photos/grand-canyon/DSC08188.webp",
        "thumb": "/photos/grand-canyon/DSC08188-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 28",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 250"
      },
      {
        "id": "grand-canyon/DSC08202",
        "full": "/photos/grand-canyon/DSC08202.webp",
        "thumb": "/photos/grand-canyon/DSC08202-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 29",
        "settings": "39mm · ƒ/22 · 1/60s · ISO 125"
      },
      {
        "id": "grand-canyon/DSC08203",
        "full": "/photos/grand-canyon/DSC08203.webp",
        "thumb": "/photos/grand-canyon/DSC08203-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 30",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08204",
        "full": "/photos/grand-canyon/DSC08204.webp",
        "thumb": "/photos/grand-canyon/DSC08204-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 31",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 200"
      },
      {
        "id": "grand-canyon/DSC08213",
        "full": "/photos/grand-canyon/DSC08213.webp",
        "thumb": "/photos/grand-canyon/DSC08213-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 32",
        "settings": "50mm · ƒ/22 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08214",
        "full": "/photos/grand-canyon/DSC08214.webp",
        "thumb": "/photos/grand-canyon/DSC08214-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 33",
        "settings": "50mm · ƒ/22 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08218",
        "full": "/photos/grand-canyon/DSC08218.webp",
        "thumb": "/photos/grand-canyon/DSC08218-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 34",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 160"
      },
      {
        "id": "grand-canyon/DSC08220",
        "full": "/photos/grand-canyon/DSC08220.webp",
        "thumb": "/photos/grand-canyon/DSC08220-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 35",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 160"
      },
      {
        "id": "grand-canyon/DSC08226",
        "full": "/photos/grand-canyon/DSC08226.webp",
        "thumb": "/photos/grand-canyon/DSC08226-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 36",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08227",
        "full": "/photos/grand-canyon/DSC08227.webp",
        "thumb": "/photos/grand-canyon/DSC08227-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 37",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 200"
      },
      {
        "id": "grand-canyon/DSC08228",
        "full": "/photos/grand-canyon/DSC08228.webp",
        "thumb": "/photos/grand-canyon/DSC08228-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 38",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08229",
        "full": "/photos/grand-canyon/DSC08229.webp",
        "thumb": "/photos/grand-canyon/DSC08229-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 39",
        "settings": "16mm · ƒ/22 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08230",
        "full": "/photos/grand-canyon/DSC08230.webp",
        "thumb": "/photos/grand-canyon/DSC08230-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 40",
        "settings": "16mm · ƒ/22 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08231",
        "full": "/photos/grand-canyon/DSC08231.webp",
        "thumb": "/photos/grand-canyon/DSC08231-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 41",
        "settings": "16mm · ƒ/22 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08277",
        "full": "/photos/grand-canyon/DSC08277.webp",
        "thumb": "/photos/grand-canyon/DSC08277-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 42",
        "settings": "50mm · ƒ/29 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08291",
        "full": "/photos/grand-canyon/DSC08291.webp",
        "thumb": "/photos/grand-canyon/DSC08291-thumb.webp",
        "width": 1333,
        "height": 2000,
        "alt": "Grand Canyon, frame 43",
        "settings": "16mm · ƒ/22 · 1/60s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08297",
        "full": "/photos/grand-canyon/DSC08297.webp",
        "thumb": "/photos/grand-canyon/DSC08297-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 44",
        "settings": "16mm · ƒ/22 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08298",
        "full": "/photos/grand-canyon/DSC08298.webp",
        "thumb": "/photos/grand-canyon/DSC08298-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 45",
        "settings": "20mm · ƒ/25 · 1/80s · ISO 100"
      },
      {
        "id": "grand-canyon/DSC08299",
        "full": "/photos/grand-canyon/DSC08299.webp",
        "thumb": "/photos/grand-canyon/DSC08299-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "Grand Canyon, frame 46",
        "settings": "44mm · ƒ/32 · 1/60s · ISO 250"
      }
    ]
  },
  {
    "slug": "first-frames",
    "title": "First Frames",
    "place": "",
    "date": "Mar 2026",
    "photos": [
      {
        "id": "first-frames/DSC08001",
        "full": "/photos/first-frames/DSC08001.webp",
        "thumb": "/photos/first-frames/DSC08001-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "First Frames, frame 1",
        "settings": "16mm · ƒ/11 · 1/20s · ISO 1600"
      },
      {
        "id": "first-frames/DSC08017",
        "full": "/photos/first-frames/DSC08017.webp",
        "thumb": "/photos/first-frames/DSC08017-thumb.webp",
        "width": 2000,
        "height": 1333,
        "alt": "First Frames, frame 2",
        "settings": "19mm · ƒ/8 · 1/125s · ISO 100"
      }
    ]
  }
];
